### ISSUE TITLE
LEDE Compatibility

### ISSUE THREAD

**Issue by MisterRager** [adde88/sslsplit-openwrt#1]
I hear LEDE is the currently prime fork of the project or something, so I updated the build scripts to [work with LEDE](https://github.com/MisterRager/sslsplit-openwrt). Since it probably clashes with the OpenWRT SDK's versions of libs, it feels like a PR against your repo isn't right. Do you want the changes in some form?

**Comment by adde88** [comment]
Thank you very much! :)
I've created a seperate branch for this 👍
