### ISSUE TITLE
Impossible to create package with OpenWrt SDK

### ISSUE THREAD

**Issue by maximushugus** [adde88/sslsplit-openwrt#2]
Hello. First I would like to thank you for your work, for creating the "Makefile" to create an OpenWrt package for sslsplit.
I'm trying, with the official SDK for Openrt for my architecture (ramips fot MT7621), to build the sslsplit package.

I cloned your repository and I put it in a repo that I specified inside the feeds.config file with the "base" and "package" feeds.
Then I updated the feeds with "./scripts/feeds update -a" and installed sslplit with "./scripts/feeds install sslsplit".

I used "make menuconfig" and unselected everything in "global build setting" because I only want to compile the sslsplit package. I selected "sslsplit" in the network section and saved the config.

When I "make", everything builds correctly, including the dependencies, build when building sslsplit I have an error and everything stops ... : I copied the error in the "error.log" file

[error.log](https://github.com/adde88/sslsplit-openwrt/files/4580941/error.log)

Do you know why I have this error ?
Thanks

**Comment by maximushugus** [comment]
Here is the [GNUmakefile.rej](https://github.com/adde88/sslsplit-openwrt/files/4580995/GNUmakefile.log) file if it can help

**Comment by adde88** [comment]
Thanks for reporting this. I was unable to reproduce your error. But i recommend trying the latest changes i just made, to see if that fixes the problem. :)

**Comment by maximushugus** [comment]
The first error I had was because when cloning this Github repo, and puting it on my local repo for the OpenWrt SDK, the name of the folder is "sslsplit-openwrt" : by renaming this folder "sslsplit" the compilation can start.

But I now have another problem : [error2.log](https://github.com/adde88/sslsplit-openwrt/files/4596146/error2.log)

It looks as if during the compilation, it cannot find libpcap, even if it's checked in the "make menuconfig" menu...
Do you know why ?

Thanks for your answer
